### ISSUE TITLE
Can't find the json file?

### ISSUE THREAD

**Issue by BrandonLSW** [fiebrink1/MaxColourTrackerForWekinator#1]
Hi there,

When I tried to run the executable program, the console showed the following error:
dict: file not found: sound_control_colourtracker_config.json
dict: file not found: sound_control_colour_scheme.json
dict: index out of range for key sensor_bg_colour
but the json files are in the same folder. Any suggestions for resolving this issue?

Thanks!

**Comment by fiebrink1** [comment]
I'm not sure. I'm not able to duplicate this. Does the colour tracker still work for you despite this?

**Comment by BrandonLSW** [comment]
@fiebrink1 Thanks for your reply. 
It seems that it worked fine with Wekinator, but I am not sure that is it tracking a right colour. Does the program depend on the parameters in the JSON files or the real-time inputs in the GUI?
<img width="573" alt="sc" src="https://user-images.githubusercontent.com/47446095/54262272-c2691680-45a8-11e9-9569-e0c6d5d07e0c.png">

**Comment by BrandonLSW** [comment]
@fiebrink1 Thanks for your reply.
It seems that it worked fine with Wekinator, but I am not sure that is it tracking a right colour. Does the program depend on the parameters in the JSON files or the real-time inputs in the GUI?
<img width="573" alt="sc" src="https://user-images.githubusercontent.com/47446095/54262659-b3369880-45a9-11e9-8bda-498a48b25ef8.png">

**Comment by fiebrink1** [comment]
The json files are just used to save your tracking preferences between sessions. If you click on the colour you want to track in the left webcam image, then adjust the tolerance, it should work for your chosen colour even without the json.

**Comment by BrandonLSW** [comment]
Got it! Thank you.
